service: king-family-photos
variablesResolutionMode: 20210326

frameworkVersion: "2"

custom:
  appName: king-family-photos-${opt:stage, 'dev'}

package:
  individually: true

provider:
  name: "aws"
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-west-2

resources:
  Resources:
    DocumentBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.appName}
        AccessControl: Private