service: king-family-photos
variablesResolutionMode: 20210326

frameworkVersion: "2"

custom:
  appName: king-family-photos-${opt:stage, 'dev'}

package:
  individually: true
  patterns:
    - '!./**'
    - ./bin/**

provider:
  name: "aws"
  runtime: go1.x
  lambdaHashingVersion: 20201221
  region: eu-west-2

resources:
  Resources:

    PhotoEventsQueue:
      Type: AWS::SQS::Queue
      Properties:
        MessageRetentionPeriod: 60
        QueueName: ${self:custom.appName}-photo-events
        VisibilityTimeout: 60

    S3EventQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      DependsOn: PhotoEventsQueue
      Properties:
        PolicyDocument:
          Statement:
            - Effect: Allow
              Sid: PutS3Events
              Action: SQS:SendMessage
              Resource: !GetAtt PhotoEventsQueue.Arn
              Principal:
                Service: photo.amazonaws.com
        Queues:
          - !Ref PhotoEventsQueue

    PhotoBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.appName}
        AccessControl: Private
        NotificationConfiguration:
          QueueConfigurations:
            - Event: photo:ObjectCreated:*
              Queue: !GetAtt PhotoEventsQueue.Arn
    
    PhotoBucketSyncPolicy:
      Type: AWS::IAM::ManagedPolicy
      DependsOn: PhotoBucket
      Properties:
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - S3:PutObject
                - S3:GetObject
              Resource: !Join [ "/", [ !GetAtt PhotoBucket.Arn, "*" ]]
            - Effect: Allow
              Action:
                - S3:ListBucket
              Resource: !GetAtt PhotoBucket.Arn

functions:
  resizeImage:
    name: ${self:custom.appName}-resize-photo
    handler: bin/resizePhoto
    events:
      - sqs:
          arn: !GetAtt PhotoEventsQueue.Arn
    