name: unit-test

on: push

jobs:
  unit-test-resizePhoto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Test resizePhoto
        working-directory: ./resizePhoto
        run: go test -v ./...

  unit-test-removePhoto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Test removePhoto
        working-directory: ./removePhoto
        run: go test -v ./...